[server]
headless = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#1E3161"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#DDE9E8"
textColor = "#1E3161"
font = "sans serif"
